### PR TITLE
Fix typos, make exception more helpful if decoding fails

### LINKED ISSUE #125: If a vector graphic fails to decode, it's very difficult to determine which one it is.
Exceptions look like this:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test (but after the test had completed):
Bad state: Unknown type tag 2

When the exception was thrown, this was the stack:
#0      VectorGraphicsCodec.decode (package:vector_graphics_codec/vector_graphics_codec.dart:177:11)
#1      decodeVectorGraphics (package:vector_graphics/src/listener.dart:54:36)
#2      _VectorGraphicWidgetState._loadPicture.<anonymous closure> (package:vector_graphics/vector_graphics.dart:223:14)
<asynchronous suspension>
(elided 2 frames from dart:async)
```

It'd be nice to include the `debugName` somewhere.

### PR DESCRIPTION
**Pull request by dnfield**
Fixes #125 

Mostly housekeeping.

### CODE REVIEW

File: packages/vector_graphics/lib/src/listener.dart [hunk 1]
```diff
@@ -41,25 +44,31 @@ Future<PictureInfo> decodeVectorGraphics(
...
+    DecodeResponse response = _codec.decode(data, listener);
+    if (response.complete) {
+      return listener.toPicture();
+    }
+    await listener.waitForImageDecode();
+    response = _codec.decode(data, listener, response: response);
+    assert(response.complete);
+
     return listener.toPicture();
+  } catch (e) {
```
Comment (jonahwilliams) [inline packages/vector_graphics/lib/src/listener.dart:69]: Can we catch exception instead of everything? As written this will catch things like NPEs, which should really just crash so we can fix it...

**Review by jonahwilliams — APPROVED** [review]
LGTM with nit

File: packages/vector_graphics/lib/src/listener.dart (hunk 1 above)
Comment (dnfield) [reply packages/vector_graphics/lib/src/listener.dart:69]: The thrown exception contains the original exception.

I want this because when dealing with an internal roll that used an invalid vector graphic binary, I couldn't tell which one was failing - only that something was causing a cast error in the codec.

Comment (jonahwilliams) [reply packages/vector_graphics/lib/src/listener.dart:69]: Makes sense!

Comment (dnfield) [reply packages/vector_graphics/lib/src/listener.dart:69]: (IOW, this is basically a catch and rethrow, just not using rethrow explicitly so I can add extra information)
